---

server:
  port: 8780

spring:
  profiles:
    include: hsql

---

spring:
  profiles: hsql
  datasource:
    url: jdbc:hsqldb:mem:rentaltrucks
    username: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database: hsql
    show-sql: true

---

spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgresql://localhost/rentaltrucks
    username: ${user.name}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
